export const Styles = () => {
  return {
    pageContainer: {
      fontFamily: "Arial",
    },
    Header: {
      color: "red",
      fontSize: "30px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px",
    },
    containingGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(10, minmax(10px, 40px))",
      gridTemplateRows: "repeat(8, minmax(20px, 40px))",
      gridGap: "5px",
      paddingBottom: "5px",
      justifyContent: "center",
      alignContent: "center",
    },
    gridItem: {
      height: "40px",
      width: "40px",
      border: "2px solid red",
      backgroundColor: "white",
      color: "red",
      fontWeight: "600",
    },
    containingButton: {
      display: "grid",
      gridTemplateColumns: "repeat(10, minmax(10px, 40px))",
      gridTemplateRows: "repeat(1, minmax(10px, 25px))",
      gridGap: "5px",
      paddingBottom: "5px",
      justifyContent: "center",
      alignContent: "center",
    },
    buttonItemContainer: {
      gridColumnStart: "-4",
      gridColumnEnd: "-1",
      border: "2px solid red",
      borderRadius: "4px",
      backgroundColor: "white",
      color: "red",
      fontWeight: "600",
    },
    defaultAmounts: {
      gridColumn: "span 2",
      border: "2px solid black",
      borderRadius: "4px",
      backgroudColor: "lightgrey",
    },
    submitButton: {
      gridColumnStart: "1",
      gridColumnEnd: "8",
      gridRowStart: "1",
      border: "2px solid black",
      borderRadius: "4px",
      backgroundColor: "	white",
      color: "black",
    },
    textField: {
      gridColumnStart: "8",
      gridColumnEnd: "-1",
      gridRowStart: "1",
      border: "2px solid black",
      borderRadius: "4px",
      backgroundColor: "white",
      color: "black",
    },
    selectedOptionsContainer: {
      display: "grid",
      gridTemplateColumns: "repeat(10, minmax(10px, 40px))",
      gridGap: "5px",
      paddingBottom: "5px",
      justifyContent: "center",
      alignContent: "center",
    },
    selectedOptions: {
      backgroundColor: "	#404040",
      border: "10px solid	#282828",
      fontSize: "20px",
      gridColumnStart: "1",
      gridColumnEnd: "-1",
    },
    selectedItemDeleteButton: {
      backgroundColor: "#404040",
      color: "white",
      border: "1px solid white",
      borderRadius: "6px",
    },
    unClickable: {
      pointerEvents: "none",
      gridColumnStart: "1",
      gridColumnEnd: "8",
      gridRowStart: "1",
      border: "2px solid black",
      borderRadius: "4px",
      backgroundColor: "	grey",
      color: "white",
    },
    clickedGrid: {
      pointerEvents: "none",
      color: "black",
      backgroundColor: "lightgrey",
      height: "40px",
      width: "40px",
      border: "2px solid lightgrey",
      fontWeight: "600",
    },
  };
};

export default Styles;
